#Область include_core_base_locale_ЛокализацияНазваниеПродукта
#КонецОбласти

#Область include_core_base_Helpers_РаботаСоСвойствамиСтруктуры
#КонецОбласти

#Область include_core_base_ExtException
#КонецОбласти

#Область include_core_base_Helpers_ФормаСбросКеша
#КонецОбласти

#Область include_base_НазваниеПродукта
#КонецОбласти

