
#Область include_BlocklyExecutor_base_Variables
#КонецОбласти

#Область include_BlocklyExecutor_base_VariableSABYHTTPClient
#КонецОбласти

// BSLLS:UnusedLocalVariable-off
// BSLLS:ExportVariables-off
Перем ГлобальныйКэш Экспорт;
// BSLLS:ExportVariables-on
// BSLLS:UnusedLocalVariable-on

#Область include_BlocklyExecutor_base_Helper
#КонецОбласти

#Область include_BlocklyExecutor_base_Helper_GetPropOnServer
#КонецОбласти

#Область include_BlocklyExecutor_base_Robots
#КонецОбласти

#Область include_BlocklyExecutor_base_ЗагрузитьФайлыНаДиск
#КонецОбласти

#Область include_BlocklyExecutor_base_Отладка
#КонецОбласти

#Область include_BlocklyExecutor_base_СконвертироватьВПДФА3
#КонецОбласти

#Область include_base_СведенияОВнешнейОбработке
#КонецОбласти

#Область include_core_base_locale_ЛокализацияНазваниеПродукта
#КонецОбласти

#Область include_BlocklyExecutor_base_API
#КонецОбласти

#Область include_BlocklyExecutor_base_APIClient
#КонецОбласти

#Область include_BlocklyExecutor_base_INIOperation
#КонецОбласти

#Область include_core_base_API
#КонецОбласти

#Область include_core_base_Helpers_ОбщиеНастройки
#КонецОбласти

#Область include_core_base_Helpers_ГлобальныйКэш
#КонецОбласти

#Область include_core_base_ДлительныеОперации_ПрогрессОперации
#КонецОбласти

#Область include_core_base_ДлительныеОперации_Модуль
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриНачалеРаботы
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриПервомЗапускеКЭДО
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриПервомЗапускеЕТРН
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриПервомЗапускеБольничные
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриПервомЗапуске
#КонецОбласти
  
#Область include_base_ОбработчикиСобытий_ПриОбновленииКонфигурации
#КонецОбласти

#Область include_core_base_ЗапускМодуля_ПриОбновленииМодуля
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриОбновленииМодуля
#КонецОбласти

#Область include_base_ОсобенностиПродукта
#КонецОбласти

#Область include_core_base_Helpers_СоздатьДополнительноеСвойствоСтатусФизЛица
#КонецОбласти

#Область include_core_base_Helpers_СоздатьДополнительноеСвойствоКЭДО
#КонецОбласти

#Область include_base_ОбработчикиСобытий_ПриОбновленииСБИС
#КонецОбласти

#Область include_core_base_ЗапускМодуля_ПриСозданииНовойИнтеграции
#КонецОбласти

#Область include_BlocklyExecutor_base_Executor
#КонецОбласти

#Область include_BlocklyExecutor_base_Workspace
#КонецОбласти

#Область include_BlocklyExecutor_base_Report
#КонецОбласти

#Область include_BlocklyExecutor_base_Action
#КонецОбласти

#Область include_BlocklyExecutor_base_Context
#КонецОбласти

#Область include_BlocklyExecutor_base_Helper_ArrayHelper
#КонецОбласти

#Область include_BlocklyExecutor_base_BlockTemplates_SimpleBlock
#КонецОбласти

#Область include_BlocklyExecutor_base_Block
#КонецОбласти

#Область include_BlocklyExecutor_base_Blocks
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks_Api3Objects
#КонецОбласти

#Область include_IntegrationBlockly_base_Blocks
#КонецОбласти

#Область include_IntegrationBlockly_base_BlocksOnServer
#КонецОбласти

#Область include_core_base_LocalHelper
#КонецОбласти

#Область include_core_base_Helpers_JSON
#КонецОбласти

#Область include_core_base_Helpers_ШифрованиеXOR
#КонецОбласти

#Область include_core_base_Helpers_ПреобразованиеТипов
#КонецОбласти

#Область include_core_base_Helpers_ПреобразованиеТиповСБИСАПИ3
#КонецОбласти

#Область include_core_base_Helpers_ОпределениеТиповКонтента
#КонецОбласти

#Область include_core_base_Транспорт_ВидТранспорта
#КонецОбласти

#Область include_core_base_Helpers
#КонецОбласти

#Область include_core_base_Helpers_ПреобразованиеТиповТаблицаМассив
#КонецОбласти

#Область include_core_base_Helpers_ИсправитьAPIURL
#КонецОбласти

#Область include_core_base_Helpers_Авторизация
#КонецОбласти

#Область include_core_base_Helpers_СовместимостьМетодов
#КонецОбласти

#Область include_core_base_Helpers_СравнениеВерсий
#КонецОбласти

#Область include_core_base_Авторизация_ПоСертификатуКлиентаМодульОбъекта
#КонецОбласти

#Область include_core_base_Helpers_ОбновитьСтруктуру
#КонецОбласти

#Область include_base_НазваниеПродукта
#КонецОбласти

#Область include_core_base_ПроверкаВерсии_ПолучитьИмяФайлаИНомерТекущейВерсии
#КонецОбласти

#Область include_core_base_ПроверкаВерсии_ВМодулеОбъекта
#КонецОбласти

#Область include_core_base_Helpers_КодироватьСтроку
#КонецОбласти

#Область include_core_base_Helpers_НастройкиПодключения
#КонецОбласти

#Область include_core_base_Helpers_ПолучитьПодключение
#КонецОбласти

#Область include_core_base_Helpers_РаботаСоСвойствамиСтруктуры
#КонецОбласти

#Область include_core_base_ExtException
#КонецОбласти

#Область include_core_base_Helpers_СтруктураПечатныхФорм
#КонецОбласти

#Область include_core_base_Helpers_ПрикрепленныеФайлы
#КонецОбласти

#Область include_core_base_Helpers_ПрикрепленныеФайлыЭДО
#КонецОбласти

#Область include_core_base_Helpers_ДвоичныеДанныеПрикрепленногоФайла
#КонецОбласти

#Область include_core_base_Helpers_ВерсияБСП
#КонецОбласти

#Область include_core_base_ОсобенностиПлатформы_МодульОбъекта
#КонецОбласти 

#Область include_core_base_ОбщийМодульКонфигурации
#КонецОбласти

#Область include_core_base_ОтправкаПриглашений
#КонецОбласти

#Область include_core_base_Криптография_БазовыеМеханизмы
#КонецОбласти

#Область include_core_base_Криптография_ЛокальнаяНаФорме
#КонецОбласти

#Область include_core_base_Криптография_Дистанционная
#КонецОбласти

#Область include_core_base_Криптография_НаСервере1С   
#КонецОбласти

#Область include_core_base_Криптография_МенеджерКриптографииБазовый
#КонецОбласти

#Область include_core_base_АвтоматическиеОперации_МодульОбработки 
#КонецОбласти 

#Область include_core_base_АвтоматическиеОперации_РегламентнаяОперация 
#КонецОбласти 

#Область include_core_base_АвтоматическиеОперации_КомандаВыполнитьАвтоматическиеОперации 
#КонецОбласти

#Область include_core_base_СтатусыДокументов_КодХраненияСтатусов
#КонецОбласти 

#Область include_core_base_СтатусыДокументов_МодульОбработки
#КонецОбласти

#Область include_core_base_ЭДО_МодульОбработки
#КонецОбласти

#Область include_core_base_Настройки_ЗагрузитьСопоставленияНаСервере
#КонецОбласти

#Область include_core_base_Транспорт_МетодыВызоваИзФорм
#КонецОбласти

#Область include_core_base_Транспорт_ПолучениеКомпоненты
#КонецОбласти

#Область include_core_base_ОсобенностиПлатформы_РаботаСоСтроками
#КонецОбласти

#Область include_core_base_Helpers_ПрефиксПродукта
#КонецОбласти

#Область include_core_base_СтатусыДокументов_ПереносСтатусов
#КонецОбласти

#Область include_core_base_Helpers_НастройкиПодключенияПризнакНаличияПлагина
#КонецОбласти

#Область include_core_base_Helpers_РаботаСМетаданными
#КонецОбласти

#Область include_core_base_ДлительныеОперации_ЗапускДлительнойОперации 
#КонецОбласти

#Область include_core_base_Helpers_ОписаниеОповещения
#КонецОбласти

#Область include_core_base_БазовыеКомпоненты_DataProcessor_ФункцииМодуля
#КонецОбласти
